parameters:
    security:
        acl:
            permission:
                map:
                    class: AdminBundle\Component\Security\Acl\Permission\KunstmaanPermissionMap
      
security:
    acl:
        connection: default
