parameters:
    kunstmaan_admin.menubuilder.class: 'Kunstmaan\AdminBundle\Helper\Menu\MenuBuilder'
    kunstmaan_admin.apply_acl_changeset.listener.class: 'Kunstmaan\AdminBundle\EventListener\ApplyAclChangesetListener'

services:
    kunstmaan_admin.menubuilder:
        class: %kunstmaan_admin.menubuilder.class%
        arguments: ["@translator", "@service_container"]

    kunstmaan_admin.menu.adaptor.settings:
        class: Kunstmaan\AdminBundle\Helper\Menu\SettingsMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
        
    kunstmaan_admin.menu.adaptor.modules:
        class: Kunstmaan\AdminBundle\Helper\Menu\ModulesMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }

    kunstmaan_admin.handler.log:
        class: Kunstmaan\AdminBundle\Helper\LogHandler
        arguments: ["@service_container"]
        tags:
            - { name: 'log_handler' }

    kunstmaan_admin.login.listener:
        class: Kunstmaan\AdminBundle\EventListener\LoginListener
        arguments: ["@security.context", "@doctrine.orm.entity_manager"]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
            
    kunstmaan_admin.menu.twig.extension:
        class: Kunstmaan\AdminBundle\Twig\Extension\MenuTwigExtension
        arguments: ["@kunstmaan_admin.menubuilder"]
        tags:
            -  { name: 'twig.extension' }

    kunstmaan_admin.localeswitcher.twig.extension:
        class: Kunstmaan\AdminBundle\Twig\Extension\LocaleSwitcherTwigExtension
        tags:
            -  { name: 'twig.extension' }

    kunstmaan_admin.locale.twig.extension:
        class: Kunstmaan\AdminBundle\Twig\Extension\DateByLocaleExtension
        tags:
            - { name: 'twig.extension' }

    kunstmaan_admin.formtools.twig.extension:
        class: Kunstmaan\AdminBundle\Twig\Extension\FormToolsExtension
        tags:
            - { name: 'twig.extension' }
 
    kunstmaan_admin.permissions.twig.extension:
        class: Kunstmaan\AdminBundle\Twig\Extension\AdminPermissionsTwigExtension
        tags:
            -  { name: 'twig.extension' }

    kunstmaan_admin.acl.helper:
        class: Kunstmaan\AdminBundle\Helper\Security\Acl\AclHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]

    kunstmaan_admin.acl.native.helper:
        class: Kunstmaan\AdminBundle\Helper\Security\Acl\AclNativeHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]

    kunstmaan_admin.guest.security.authentication.listener:
        class: Kunstmaan\AdminBundle\Helper\Security\Http\Firewall\GuestUserListener
        arguments: ["@security.context", "user_provider", "provider_key"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
        
    kunstmaan_admin.permissionadmin:
        class: Kunstmaan\AdminBundle\Helper\Security\Acl\Permission\PermissionAdmin
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@security.acl.provider", "@security.acl.object_identity_retrieval_strategy", "@event_dispatcher", "@kunstmaan_utilities.shell", "@kernel"]

    kunstmaan_admin.clone.helper:
        class: Kunstmaan\AdminBundle\Helper\CloneHelper
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]

    kunstmaan_admin.clone.listener:
        class: Kunstmaan\AdminBundle\EventListener\CloneListener
        tags:
            - { name: kernel.event_listener, event: kunstmaan_admin.onDeepCloneAndSave, method: onDeepCloneAndSave }
